
### get all contact 

GET http://localhost:2909/contacts


### get contact by id

GET http://localhost:2909/contacts/6a5ff999c11bb3f5ebbc3bae

### Insert one contact

POST http://localhost:2909/contacts
Content-Type: application/json

{
  "firstName": "MANGANGA - MBEDI",
  "lastName": "medi - veniel",
  "email": "venie@gmail.com",
  "favoriteColor": "Black",
  "birthday": "2002-09-29"
}


### Update one contact

PUT  http://localhost:2909/contacts/6a5ff80a1ff343ae196f8144
Content-Type: application/json

{
  "firstName": "MAREINE MBEDI",
  "lastName": "medi",
  "email": "liza@gmail.com",
  "favoriteColor": "Yellow",
  "birthday": "2002-09-29"
}

### Delete one contact
DELETE http://localhost:2909/contacts/6a5ffe64949259ec1ccdd0e9

### using render
GET https://cse341-week1-ot1d.onrender.com/contacts

### using render
POST https://cse341-week1-ot1d.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "MANGANGA - MBEDI",
  "lastName": "medi - veniel",
  "email": "venie@gmail.com",
  "favoriteColor": "Black",
  "birthday": "2002-09-29"
}